import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("my_data.csv")

#Limpieza
df["Desarrollador"] = df["Desarrollador"].str.strip('Desarrollador')
df["Desarrollador"] = df["Desarrollador"].str.strip('"')

df["Género"] = df["Género"].str.replace("Acció","Acción")
df["Género"] = df["Género"].str.replace("Acciónn","Acción")

df["Género"] = df["Género"].str.replace("Conducció","Conducción")
df["Género"] = df["Género"].str.replace("Conducciónn","Conducción")

df["Género"] = df["Género"].str.replace("Simulació","Simulación")
df["Género"] = df["Género"].str.replace("Simulaciónn","Simulación")

df["Popularidad"] = df["Popularidad"].str.replace("Magnífic","Magnífica")
df["Popularidad"] = df["Popularidad"].str.replace("Magníficaa","Magnífica")
df["Popularidad"] = df["Popularidad"].str.replace("Escas","Escasa")
df["Popularidad"] = df["Popularidad"].str.replace("Escasaa","Escasa")

df["Jugadores"] = df["Jugadores"].str.strip('"Jugadores:')
df["Jugadores"] = df["Jugadores"].str.replace("Multij","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("1-Multij","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("Cooperativ","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("1-2","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("2-8","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace('1.4',"Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("2-16","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("2-6","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("1-4","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("2-4","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("1-5","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("1-6","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("1-3","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("Masiv","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-22","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-40","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("12","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-12","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-8","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-10","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-100","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-48","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-60","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-128","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-16","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-32","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-64","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-25","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("Un","1")
df["Jugadores"] = df["Jugadores"].str.replace("1-20","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("15-30","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-24","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("nlin","1")
df["Jugadores"] = df["Jugadores"].str.replace("nlin","1")
df["Jugadores"] = df["Jugadores"].str.replace("Multijugadorugador","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("Multijugadorugador0","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("Multijugador2","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("Multijugador4","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("Multijugador8","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("Cooperativoo2","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("Cooperativo2","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("Cooperativo5","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("Cooperativo0","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("Cooperativo4","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("2","Cooperativo")
df["Jugadores"] = df["Jugadores"].str.replace("1-Masivo8","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("10","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("1-Masivo","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("Masivo0","Masivo")
df["Jugadores"] = df["Jugadores"].str.replace("Multijugador0","Multijugador")
df["Jugadores"] = df["Jugadores"].str.replace("Competitiv","Competitivo")

literal1 = df.loc[df['Precio']>0]
literal1.reset_index(drop=True,inplace=True)
literal1 = literal1.groupby('Popularidad')['Precio'].mean().reset_index()
fig,ax = plt.subplots(figsize=(12,8))
ax = sns.barplot(data=literal1.sort_values(by="Precio", ascending = False)
, x="Precio", y="Popularidad", orient="h")
fig.show()

literal2 = df.copy()
literal2 = literal2.loc[literal2['Jugadores'].notnull()]
literal2["Popularidad"] = literal2["Popularidad"].str.replace("Magnífica","5")
literal2["Popularidad"] = literal2["Popularidad"].str.replace("Excelente","4")
literal2["Popularidad"] = literal2["Popularidad"].str.replace("Notable","3")
literal2["Popularidad"] = literal2["Popularidad"].str.replace("Apreciable","2")
literal2["Popularidad"] = literal2["Popularidad"].str.replace("Escasa","1")
literal2["Popularidad"] = literal2["Popularidad"].str.strip("").astype("int64")
literal2[['Rol', 'Acción', 'Deportes', 'Estrategia', 'Aventura', 'Otros', 'Conducción', 'Simulación']] = pd.get_dummies(literal2["Género"])
literal2[['1', 'Cooperativo', 'Multijugador', 'Masivo', 'Competitivo']] = pd.get_dummies(literal2["Jugadores"])
print(literal2.corr())

top =df.groupby('Desarrollador')['Nombre'].count().reset_index().sort_values(by=['Nombre'], ascending=False).head(10)["Desarrollador"].unique()
literal3 = pd.DataFrame()               
for i in range(top.size):
    literal3 = pd.concat([df[df["Desarrollador"]==top[i]], literal3], axis=0)
literal3.reset_index(inplace=True, drop=True)
literal31 = literal3.groupby('Género')['Nombre'].count().reset_index()
literal31['Cantidad'] = literal31['Nombre']
fig,ax = plt.subplots(figsize=(12,8))
ax = sns.barplot(data=literal31.sort_values(by="Cantidad", ascending = False)
, x="Cantidad", y="Género", orient="h")
fig.show()


df.to_csv('dataFinal.csv',sep=';')